import globals from 'globals';
import babelParser from '@babel/eslint-parser';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import js from '@eslint/js';
import {FlatCompat} from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all
});

export default [...compat.extends('eslint:recommended'), {
  plugins: {},

  languageOptions: {
    globals: {
      ...globals.node,
    },

    parser: babelParser,
    parserOptions: {
      requireConfigFile: false,
      babelOptions: {
        babelrc: false,
        configFile: false,
        presets: ['@babel/preset-env']
      }
    }
  },

  rules: {
    'comma-dangle': 0,
    'no-cond-assign': 2,
    'no-console': 2,
    'no-constant-condition': 1,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 2,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': 1,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-prototype-builtins': 2,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 1,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'use-isnan': 2,
    'valid-typeof': 2,
    'accessor-pairs': 0,
    'array-callback-return': 2,
    'block-scoped-var': 2,
    complexity: 1,
    'consistent-return': 0,
    curly: 2,
    'default-case': 2,
    'dot-location': [2, 'property'],
    'dot-notation': 2,
    eqeqeq: 2,
    'guard-for-in': 2,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 0,
    'no-div-regex': 2,
    'no-else-return': 0,
    'no-empty-function': 2,
    'no-empty-pattern': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 0,
    'no-extra-bind': 1,
    'no-extra-label': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-implicit-coercion': 0,
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-invalid-this': 2,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,

    'no-magic-numbers': [2, {
      ignore: [0, 1, -1],
    }],

    'no-multi-spaces': 2,
    'no-multi-str': 0,
    'no-native-reassign': 2,
    'no-new-func': 1,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 0,
    'no-octal': 0,
    'no-param-reassign': 2,
    'no-process-env': 2,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 0,
    'no-unmodified-loop-condition': 2,
    'no-unused-expressions': 0,
    'no-unused-labels': 2,
    'no-useless-call': 2,
    'no-useless-concat': 2,
    'no-useless-escape': 2,
    'no-void': 0,
    'no-warning-comments': 1,
    'no-with': 2,
    radix: 2,
    'vars-on-top': 0,
    'wrap-iife': 2,
    yoda: 2,
    strict: 0,
    'init-declarations': 0,
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-restricted-globals': 0,
    'no-shadow-restricted-names': 2,

    'no-shadow': [2, {
      allow: ['err'],
    }],

    'no-undef-init': 2,
    'no-undef': 2,
    'no-undefined': 0,
    'no-unused-vars': 2,

    'no-use-before-define': [2, {
      functions: false,
    }],

    'callback-return': 2,
    'global-require': 0,
    'handle-callback-err': 2,
    'no-mixed-requires': 2,
    'no-new-require': 2,
    'no-path-concat': 2,
    'no-process-exit': 2,
    'no-restricted-imports': 0,
    'no-restricted-modules': 0,
    'no-sync': 1,
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': 0,
    'brace-style': 2,
    camelcase: 1,

    'comma-spacing': [2, {
      before: false,
      after: true,
    }],

    'comma-style': 2,
    'computed-property-spacing': 2,
    'consistent-this': 2,
    'eol-last': 2,
    'func-names': 0,
    'func-style': 0,
    'id-blacklist': 0,

    'id-length': [2, {
      min: 2,
      max: 45,
      exceptions: ['_'],
    }],

    'id-match': 0,
    indent: ['error', 2],
    'jsx-quotes': 0,
    'key-spacing': 2,

    'keyword-spacing': [2, {
      before: true,
      after: true,
    }],

    'linebreak-style': 2,

    'lines-around-comment': ['error', {
      beforeLineComment: true,
      allowBlockStart: true,
    }],

    'max-depth': 1,
    'max-len': [1, 120],
    'max-lines': [1, 500],
    'max-nested-callbacks': 2,
    'max-params': [1, 5],
    'max-statements': [1, 50],
    'max-statements-per-line': 1,
    'new-cap': 0,
    'new-parens': 2,
    'newline-after-var': 0,
    'newline-before-return': 2,
    'newline-per-chained-call': 0,
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-continue': 0,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-operators': 0,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': 2,
    'no-negated-condition': 0,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': 0,
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'object-curly-newline': 2,
    'object-curly-spacing': 2,

    'object-property-newline': [2, {
      allowAllPropertiesOnSameLine: true,
    }],

    'one-var': [2, 'never'],
    'one-var-declaration-per-line': 2,
    'operator-assignment': 0,
    'operator-linebreak': [1, 'before'],
    'padded-blocks': 0,
    'quote-props': [2, 'as-needed'],
    quotes: [2, 'single'],
    'require-jsdoc': 0,
    'semi-spacing': 2,
    'sort-imports': 0,
    semi: 2,
    'sort-vars': 0,
    'space-before-blocks': 2,
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': 2,
    'space-infix-ops': 2,
    'space-unary-ops': 2,

    'spaced-comment': [2, 'always', {
      exceptions: ['*'],
    }],

    'unicode-bom': 0,
    'wrap-regex': 0,
    'arrow-body-style': [2, 'as-needed'],
    'arrow-parens': [2, 'as-needed'],
    'arrow-spacing': 2,
    'constructor-super': 2,
    'generator-star-spacing': 0,
    'no-class-assign': 2,
    'no-confusing-arrow': 2,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-duplicate-imports': 2,
    'no-new-symbol': 2,
    'no-this-before-super': 2,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-rename': 2,
    'no-var': 0,
    'object-shorthand': 1,
    'prefer-arrow-callback': 1,
    'prefer-const': 0,
    'prefer-rest-params': 1,
    'prefer-spread': 1,
    'prefer-template': 1,
    'require-yield': 0,
    'rest-spread-spacing': ['error', 'never'],
    'template-curly-spacing': 2,
    'yield-star-spacing': [2, 'after'],
  },
}, {
  files: ['**/*.integration.js', '**/*.spec.js'],

  rules: {
    'no-magic-numbers': 'off',
  },
}, {
  files: ['**/*.js'],

  rules: {
    'prefer-arrow-callback': 0,
    'no-process-env': 0,
    'no-warning-comments': 0,
    'prefer-template': 0,
    'no-sync': 0,
  },
}];
