/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSettingsModal: typeof import('./src/components/AdvancedSettingsModal.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    Blockchain: typeof import('./src/components/Blockchain.vue')['default']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    CardWidget: typeof import('./src/components/CardWidget.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    ChartEmptyState: typeof import('./src/components/ChartEmptyState.vue')['default']
    ChartWrapper: typeof import('./src/components/ChartWrapper.vue')['default']
    ConnectionModal: typeof import('./src/components/ConnectionModal.vue')['default']
    CountUp: typeof import('./src/components/Utility/CountUp.vue')['default']
    DonationModal: typeof import('./src/components/DonationModal.vue')['default']
    IcRoundPlus: typeof import('~icons/ic/round-plus')['default']
    InputCopy: typeof import('./src/components/Utility/InputCopy.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MinerSlider: typeof import('./src/components/MinerSlider.vue')['default']
    PruneSlider: typeof import('./src/components/PruneSlider.vue')['default']
    QrCode: typeof import('./src/components/Utility/QrCode.vue')['default']
    QrCodeMonero: typeof import('./src/components/Utility/QrCodeMonero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stat: typeof import('./src/components/Utility/Stat.vue')['default']
    Status: typeof import('./src/components/Utility/Status.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
    ToggleSwitch: typeof import('./src/components/Utility/ToggleSwitch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
